var myMarkupSet = 
[
	{separator: '---------------'},
	{name: 'People', className:'emoji-people', dropMenu: [
		{name: 'Smile', openWith: ' :smile: '},
		{name: 'Smiley', openWith: ' :smiley: '},
		{name: 'Grinning', openWith: ' :grinning: '},
		{name: 'Blush', openWith: ' :blush: '},
		{name: 'Relaxed', openWith: ' :relaxed: '},
		{name: 'Wink', openWith: ' :wink: '},
		{name: 'Heart Eyes', openWith: ' :heart_eyes: '},
		{name: 'Kissing Heart', openWith: ' :kissing_heart: '},
		{name: 'Kissing Closed Eyes', openWith: ' :kissing_closed_eyes: '},
		{name: 'Kissing', openWith: ' :kissing: '},
		{name: 'Kissing Smiling Eyes', openWith: ' :kissing_smiling_eyes: '},
		{name: 'Wink2', openWith: ' :stuck_out_tongue_winking_eye: '},
		{name: 'Stuck out Tongue Closed Eyes', openWith: ' :stuck_out_tongue_closed_eyes: '},
		{name: 'Stuck out Tongue', openWith: ' :stuck_out_tongue: '},
		{name: 'Flushed', openWith: ' :flushed: '},
		{name: 'Grin', openWith: ' :grin: '},
		{name: 'Pensive', openWith: ' :pensive: '},
		{name: 'Satisfied', openWith: ' :satisfied: '},
		{name: 'Unamused', openWith: ' :unamused: '},
		{name: 'Disappointed', openWith: ' :disappointed: '},
		{name: 'Persevere', openWith: ' :persevere: '},
		{name: 'Cry', openWith: ' :cry: '},
		{name: 'Joy', openWith: ' :joy: '},
		{name: 'Sob', openWith: ' :sob: '},
		{name: 'Sleepy', openWith: ' :sleepy: '},
		{name: 'Relieved', openWith: ' :relieved: '},
		{name: 'Cold Sweat', openWith: ' :cold_sweat: '},
		{name: 'Sweat Smile', openWith: ' :sweat_smile: '},
		{name: 'Sweat', openWith: ' :sweat: '},
		{name: 'Weary', openWith: ' :weary: '},
		{name: 'Tired Face', openWith: ' :tired_face: '},
		{name: 'Fearful', openWith: ' :fearful: '},
		{name: 'Scream', openWith: ' :scream: '},
		{name: 'Angry', openWith: ' :angry: '},
		{name: 'Rage', openWith: ' :rage: '},
		{name: 'Triumph', openWith: ' :triumph: '},
		{name: 'Confounded', openWith: ' :confounded: '},
		{name: 'Laughing', openWith: ' :laughing: '},
		{name: 'Yum', openWith: ' :yum: '},
		{name: 'Mask', openWith: ' :mask: '},
		{name: 'Sunglasses', openWith: ' :sunglasses: '},
		{name: 'Sleeping', openWith: ' :sleeping: '},
		{name: 'Dizzy Face', openWith: ' :dizzy_face: '},
		{name: 'Astonished', openWith: ' :astonished: '},
		{name: 'Worried', openWith: ' :worried: '},
		{name: 'Frowning', openWith: ' :frowning: '},
		{name: 'Anguished', openWith: ' :anguished: '},
		{name: 'Smiling Imp', openWith: ' :smiling_imp: '},
		{name: 'Imp', openWith: ' :imp: '},
		{name: 'Open Mouth', openWith: ' :open_mouth: '},
		{name: 'Grimacing', openWith: ' :grimacing: '},
		{name: 'Neutral Face', openWith: ' :neutral_face: '},
		{name: 'Confused', openWith: ' :confused: '},
		{name: 'Hushed', openWith: ' :hushed: '},
		{name: 'No Mouth', openWith: ' :no_mouth: '},
		{name: 'Innocent', openWith: ' :innocent: '},
		{name: 'Smirk', openWith: ' :smirk: '},
		{name: 'Expressionless', openWith: ' :expressionless: '},
		{name: 'Man With Gua Pi Mao', openWith: ' :man_with_gua_pi_mao: '},
		{name: 'Man With Turban', openWith: ' :man_with_turban: '},
		{name: 'Cop', openWith: ' :cop: '},
		{name: 'Construction Worker', openWith: ' :construction_worker: '},
		{name: 'Guardsman', openWith: ' :guardsman: '},
		{name: 'Baby', openWith: ' :baby: '},
		{name: 'Boy', openWith: ' :boy: '},
		{name: 'Girl', openWith: ' :girl: '},
		{name: 'Man', openWith: ' :man: '},
		{name: 'Woman', openWith: ' :woman: '},
		{name: 'Older Man', openWith: ' :older_man: '},
		{name: 'Older Woman', openWith: ' :older_woman: '},
		{name: 'Person With Blond Hair', openWith: ' :person_with_blond_hair: '},
		{name: 'Angel', openWith: ' :angel: '},
		{name: 'Princess', openWith: ' :princess: '},
		{name: 'Smiley Cat', openWith: ' :smiley_cat: '},
		{name: 'Smile Cat', openWith: ' :smile_cat: '},
		{name: 'Heart Eyes Cat', openWith: ' :heart_eyes_cat: '},
		{name: 'Kissing Cat', openWith: ' :kissing_cat: '},
		{name: 'Smirk Cat', openWith: ' :smirk_cat: '},
		{name: 'Scream Cat', openWith: ' :scream_cat: '},
		{name: 'Crying Cat Face', openWith: ' :crying_cat_face: '},
		{name: 'Joy Cat', openWith: ' :joy_cat: '},
		{name: 'Pouting Cat', openWith: ' :pouting_cat: '},
		{name: 'Japanese Ogre', openWith: ' :japanese_ogre: '},
		{name: 'Japanese Goblin', openWith: ' :japanese_goblin: '},
		{name: 'See No Evil', openWith: ' :see_no_evil: '},
		{name: 'Hear No Evil', openWith: ' :hear_no_evil: '},
		{name: 'Speak No Evil', openWith: ' :speak_no_evil: '},
		{name: 'Skull', openWith: ' :skull: '},
		{name: 'Alien', openWith: ' :alien: '},
		{name: 'Poop', openWith: ' :poop: '},
		{name: 'Fire', openWith: ' :fire: '},
		{name: 'Sparkles', openWith: ' :sparkles: '},
		{name: 'Star2', openWith: ' :star2: '},
		{name: 'Dizzy', openWith: ' :dizzy: '},
		{name: 'Boom', openWith: ' :boom: '},
		{name: 'Anger', openWith: ' :anger: '},
		{name: 'Sweat Drops', openWith: ' :sweat_drops: '},
		{name: 'Droplet', openWith: ' :droplet: '},
		{name: 'Zzz', openWith: ' :zzz: '},
		{name: 'Dash', openWith: ' :dash: '},
		{name: 'Ear', openWith: ' :ear: '},
		{name: 'Eyes', openWith: ' :eyes: '},
		{name: 'Nose', openWith: ' :nose: '},
		{name: 'Tongue', openWith: ' :tongue: '},
		{name: 'Lips', openWith: ' :lips: '},
		{name: 'Thumbsup', openWith: ' :thumbsup: '},
		{name: 'Thumbsdown', openWith: ' :thumbsdown: '},
		{name: 'Ok Hand', openWith: ' :ok_hand: '},
		{name: 'Punch', openWith: ' :punch: '},
		{name: 'Fist', openWith: ' :fist: '},
		{name: 'V', openWith: ' :v: '},
		{name: 'Wave', openWith: ' :wave: '},
		{name: 'Hand', openWith: ' :raised_hand: '},
		{name: 'Open Hands', openWith: ' :open_hands: '},
		{name: 'Point up 2', openWith: ' :point_up_2: '},
		{name: 'Point Down', openWith: ' :point_down: '},
		{name: 'Point Right', openWith: ' :point_right: '},
		{name: 'Point Left', openWith: ' :point_left: '},
		{name: 'Raised Hands', openWith: ' :raised_hands: '},
		{name: 'Pray', openWith: ' :pray: '},
		{name: 'Point up', openWith: ' :point_up: '},
		{name: 'Clap', openWith: ' :clap: '},
		{name: 'Muscle', openWith: ' :muscle: '},
		{name: 'Walking', openWith: ' :walking: '},
		{name: 'Running', openWith: ' :runner: '},
		{name: 'Dancer', openWith: ' :dancer: '},
		{name: 'Couple', openWith: ' :couple: '},
		{name: 'Family', openWith: ' :family: '},
		{name: 'Two Men Holding Hands', openWith: ' :two_men_holding_hands: '},
		{name: 'Two Women Holding Hands', openWith: ' :two_women_holding_hands: '},
		{name: 'Couplekiss', openWith: ' :couplekiss: '},
		{name: 'Couple With Heart', openWith: ' :couple_with_heart: '},
		{name: 'Dancers', openWith: ' :dancers: '},
		{name: 'Ok Woman', openWith: ' :ok_woman: '},
		{name: 'No Good', openWith: ' :no_good: '},
		{name: 'Information Desk Person', openWith: ' :information_desk_person: '},
		{name: 'Raised Hand', openWith: ' :raised_hand: '},
		{name: 'Massage', openWith: ' :massage: '},
		{name: 'Haircut', openWith: ' :haircut: '},
		{name: 'Nail Care', openWith: ' :nail_care: '},
		{name: 'Bride With Veil', openWith: ' :bride_with_veil: '},
		{name: 'Person With Pouting Face', openWith: ' :person_with_pouting_face: '},
		{name: 'Person Frowning', openWith: ' :person_frowning: '},
		{name: 'Bow', openWith: ' :bow: '},
		{name: 'Tophat', openWith: ' :tophat: '},
		{name: 'Crown', openWith: ' :crown: '},
		{name: 'Womans Hat', openWith: ' :womans_hat: '},
		{name: 'Shoe', openWith: ' :athletic_shoe: '},
		{name: 'Mans Shoe', openWith: ' :mans_shoe: '},
		{name: 'Sandal', openWith: ' :sandal: '},
		{name: 'High Heel', openWith: ' :high_heel: '},
		{name: 'Boot', openWith: ' :boot: '},
		{name: 'Shirt', openWith: ' :shirt: '},
		{name: 'Necktie', openWith: ' :necktie: '},
		{name: 'Womans Clothes', openWith: ' :womans_clothes: '},
		{name: 'Dress', openWith: ' :dress: '},
		{name: 'Running Shirt With Sash', openWith: ' :running_shirt_with_sash: '},
		{name: 'Jeans', openWith: ' :jeans: '},
		{name: 'Kimono', openWith: ' :kimono: '},
		{name: 'Bikini', openWith: ' :bikini: '},
		{name: 'Briefcase', openWith: ' :briefcase: '},
		{name: 'Handbag', openWith: ' :handbag: '},
		{name: 'Pouch', openWith: ' :pouch: '},
		{name: 'Purse', openWith: ' :purse: '},
		{name: 'Eyeglasses', openWith: ' :eyeglasses: '},
		{name: 'Ribbon', openWith: ' :ribbon: '},
		{name: 'Closed Umbrella', openWith: ' :closed_umbrella: '},
		{name: 'Lipstick', openWith: ' :lipstick: '},
		{name: 'Yellow Heart', openWith: ' :yellow_heart: '},
		{name: 'Blue Heart', openWith: ' :blue_heart: '},
		{name: 'Purple Heart', openWith: ' :purple_heart: '},
		{name: 'Green Heart', openWith: ' :green_heart: '},
		{name: 'Heart', openWith: ' :heart: '},
		{name: 'Broken Heart', openWith: ' :broken_heart: '},
		{name: 'Heartpulse', openWith: ' :heartpulse: '},
		{name: 'Heartbeat', openWith: ' :heartbeat: '},
		{name: 'Two Hearts', openWith: ' :two_hearts: '},
		{name: 'Sparkling Heart', openWith: ' :sparkling_heart: '},
		{name: 'Revolving Hearts', openWith: ' :revolving_hearts: '},
		{name: 'Cupid', openWith: ' :cupid: '},
		{name: 'Valentine', openWith: ' :love_letter: '},
		{name: 'Kiss', openWith: ' :kiss: '},
		{name: 'Ring', openWith: ' :ring: '},
		{name: 'Gem', openWith: ' :gem: '},
		{name: 'Bust in Silhouette', openWith: ' :bust_in_silhouette: '},
		{name: 'Busts in Silhouette', openWith: ' :busts_in_silhouette: '},
		{name: 'Speech Balloon', openWith: ' :speech_balloon: '},
		{name: 'Feet', openWith: ' :feet: '},
		{name: 'Thought Balloon', openWith: ' :thought_balloon: '}
	]},
	{name: 'Nature', className:'emoji-nature', dropMenu: [
		{name: 'Dog', openWith: ' :dog: '},
		{name: 'Wolf', openWith: ' :wolf: '},
		{name: 'Cat', openWith: ' :cat: '},
		{name: 'Mouse', openWith: ' :mouse: '},
		{name: 'Hamster', openWith: ' :hamster: '},
		{name: 'Rabbit', openWith: ' :rabbit: '},
		{name: 'Frog', openWith: ' :frog: '},
		{name: 'Tiger', openWith: ' :tiger: '},
		{name: 'Koala', openWith: ' :koala: '},
		{name: 'Bear', openWith: ' :bear: '},
		{name: 'Pig', openWith: ' :pig: '},
		{name: 'Pig Nose', openWith: ' :pig_nose: '},
		{name: 'Cow', openWith: ' :cow: '},
		{name: 'Boar', openWith: ' :boar: '},
		{name: 'Monkey Face', openWith: ' :monkey_face: '},
		{name: 'Monkey', openWith: ' :monkey: '},
		{name: 'Horse', openWith: ' :horse: '},
		{name: 'Sheep', openWith: ' :sheep: '},
		{name: 'Elephant', openWith: ' :elephant: '},
		{name: 'Panda Face', openWith: ' :panda_face: '},
		{name: 'Penguin', openWith: ' :penguin: '},
		{name: 'Bird', openWith: ' :bird: '},
		{name: 'Baby Chick', openWith: ' :baby_chick: '},
		{name: 'Hatched Chick', openWith: ' :hatched_chick: '},
		{name: 'Hatching Chick', openWith: ' :hatching_chick: '},
		{name: 'Chicken', openWith: ' :chicken: '},
		{name: 'Snake', openWith: ' :snake: '},
		{name: 'Turtle', openWith: ' :turtle: '},
		{name: 'Bug', openWith: ' :bug: '},
		{name: 'Honeybee', openWith: ' :bee: '},
		{name: 'Ant', openWith: ' :ant: '},
		{name: 'Beetle', openWith: ' :beetle: '},
		{name: 'Snail', openWith: ' :snail: '},
		{name: 'Octopus', openWith: ' :octopus: '},
		{name: 'Shell', openWith: ' :shell: '},
		{name: 'Tropical Fish', openWith: ' :tropical_fish: '},
		{name: 'Fish', openWith: ' :fish: '},
		{name: 'Dolphin', openWith: ' :dolphin: '},
		{name: 'Whale', openWith: ' :whale: '},
		{name: 'Whale2', openWith: ' :whale2: '},
		{name: 'Cow2', openWith: ' :cow2: '},
		{name: 'Ram', openWith: ' :ram: '},
		{name: 'Rat', openWith: ' :rat: '},
		{name: 'Water Buffalo', openWith: ' :water_buffalo: '},
		{name: 'Tiger2', openWith: ' :tiger2: '},
		{name: 'Rabbit2', openWith: ' :rabbit2: '},
		{name: 'Dragon', openWith: ' :dragon: '},
		{name: 'Racehorse', openWith: ' :racehorse: '},
		{name: 'Goat', openWith: ' :goat: '},
		{name: 'Rooster', openWith: ' :rooster: '},
		{name: 'Dog2', openWith: ' :dog2: '},
		{name: 'Pig2', openWith: ' :pig2: '},
		{name: 'Mouse2', openWith: ' :mouse2: '},
		{name: 'Ox', openWith: ' :ox: '},
		{name: 'Dragon Face', openWith: ' :dragon_face: '},
		{name: 'Blowfish', openWith: ' :blowfish: '},
		{name: 'Crocodile', openWith: ' :crocodile: '},
		{name: 'Camel', openWith: ' :camel: '},
		{name: 'Dromedary Camel', openWith: ' :dromedary_camel: '},
		{name: 'Leopard', openWith: ' :leopard: '},
		{name: 'Cat2', openWith: ' :cat2: '},
		{name: 'Poodle', openWith: ' :poodle: '},
		{name: 'Paw Prints', openWith: ' :feet: '},
		{name: 'Bouquet', openWith: ' :bouquet: '},
		{name: 'Cherry Blossom', openWith: ' :cherry_blossom: '},
		{name: 'Tulip', openWith: ' :tulip: '},
		{name: 'Four Leaf Clover', openWith: ' :four_leaf_clover: '},
		{name: 'Rose', openWith: ' :rose: '},
		{name: 'Sunflower', openWith: ' :sunflower: '},
		{name: 'Hibiscus', openWith: ' :hibiscus: '},
		{name: 'Maple Leaf', openWith: ' :maple_leaf: '},
		{name: 'Leaves', openWith: ' :leaves: '},
		{name: 'Fallen Leaf', openWith: ' :fallen_leaf: '},
		{name: 'Herb', openWith: ' :herb: '},
		{name: 'Ear of Rice', openWith: ' :ear_of_rice: '},
		{name: 'Mushroom', openWith: ' :mushroom: '},
		{name: 'Cactus', openWith: ' :cactus: '},
		{name: 'Palm Tree', openWith: ' :palm_tree: '},
		{name: 'Evergreen Tree', openWith: ' :evergreen_tree: '},
		{name: 'Deciduous Tree', openWith: ' :deciduous_tree: '},
		{name: 'Chestnut', openWith: ' :chestnut: '},
		{name: 'Seedling', openWith: ' :seedling: '},
		{name: 'Blossom', openWith: ' :blossom: '},
		{name: 'Globe With Meridians', openWith: ' :globe_with_meridians: '},
		{name: 'Sun With Face', openWith: ' :sun_with_face: '},
		{name: 'Full Moon With Face', openWith: ' :full_moon_with_face: '},
		{name: 'New Moon With Face', openWith: ' :new_moon_with_face: '},
		{name: 'New Moon', openWith: ' :new_moon: '},
		{name: 'Waxing Crescent Moon', openWith: ' :waxing_crescent_moon: '},
		{name: 'First Quarter Moon', openWith: ' :first_quarter_moon: '},
		{name: 'Waxing Gibbous Moon', openWith: ' :waxing_gibbous_moon: '},
		{name: 'Full Moon', openWith: ' :full_moon: '},
		{name: 'Waning Gibbous Moon', openWith: ' :waning_gibbous_moon: '},
		{name: 'Last Quarter Moon', openWith: ' :last_quarter_moon: '},
		{name: 'Waning Crescent Moon', openWith: ' :waning_crescent_moon: '},
		{name: 'Last Quarter Moon With Face', openWith: ' :last_quarter_moon_with_face: '},
		{name: 'First Quarter Moon With Face', openWith: ' :first_quarter_moon_with_face: '},
		{name: 'Moon', openWith: ' :crescent_moon: '},
		{name: 'Earth Africa', openWith: ' :earth_africa: '},
		{name: 'Earth Americas', openWith: ' :earth_americas: '},
		{name: 'Earth Asia', openWith: ' :earth_asia: '},
		{name: 'Volcano', openWith: ' :volcano: '},
		{name: 'Milky Way', openWith: ' :milky_way: '},
		{name: 'Stars', openWith: ' :stars: '},
		{name: 'Star', openWith: ' :star: '},
		{name: 'Sunny', openWith: ' :sunny: '},
		{name: 'Partly Sunny', openWith: ' :partly_sunny: '},
		{name: 'Cloud', openWith: ' :cloud: '},
		{name: 'Zap', openWith: ' :zap: '},
		{name: 'Umbrella', openWith: ' :umbrella: '},
		{name: 'Snowflake', openWith: ' :snowflake: '},
		{name: 'Snowman', openWith: ' :snowman: '},
		{name: 'Cyclone', openWith: ' :cyclone: '},
		{name: 'Foggy', openWith: ' :foggy: '},
		{name: 'Rainbow', openWith: ' :rainbow: '},
		{name: 'Ocean', openWith: ' :ocean: '}
	]},
	{name: 'Objects', className:'emoji-objects', dropMenu: [
		{name: 'Bamboo', openWith: ' :bamboo: '},
		{name: 'Gift Heart', openWith: ' :gift_heart: '},
		{name: 'Dolls', openWith: ' :dolls: '},
		{name: 'School Satchel', openWith: ' :school_satchel: '},
		{name: 'Mortar Board', openWith: ' :mortar_board: '},
		{name: 'Flags', openWith: ' :flags: '},
		{name: 'Fireworks', openWith: ' :fireworks: '},
		{name: 'Sparkler', openWith: ' :sparkler: '},
		{name: 'Wind Chime', openWith: ' :wind_chime: '},
		{name: 'Rice Scene', openWith: ' :rice_scene: '},
		{name: 'Jack O Lantern', openWith: ' :jack_o_lantern: '},
		{name: 'Ghost', openWith: ' :ghost: '},
		{name: 'Santa', openWith: ' :santa: '},
		{name: 'Christmas Tree', openWith: ' :christmas_tree: '},
		{name: 'Gift', openWith: ' :gift: '},
		{name: 'Tanabata Tree', openWith: ' :tanabata_tree: '},
		{name: 'Tada', openWith: ' :tada: '},
		{name: 'Confetti Ball', openWith: ' :confetti_ball: '},
		{name: 'Balloon', openWith: ' :balloon: '},
		{name: 'Crossed Flags', openWith: ' :crossed_flags: '},
		{name: 'Crystal Ball', openWith: ' :crystal_ball: '},
		{name: 'Movie Camera', openWith: ' :movie_camera: '},
		{name: 'Camera', openWith: ' :camera: '},
		{name: 'Video Camera', openWith: ' :video_camera: '},
		{name: 'Vhs', openWith: ' :vhs: '},
		{name: 'Cd', openWith: ' :cd: '},
		{name: 'Dvd', openWith: ' :dvd: '},
		{name: 'Minidisc', openWith: ' :minidisc: '},
		{name: 'Floppy Disk', openWith: ' :floppy_disk: '},
		{name: 'Computer', openWith: ' :computer: '},
		{name: 'Iphone', openWith: ' :iphone: '},
		{name: 'Phone', openWith: ' :telephone: '},
		{name: 'Telephone Receiver', openWith: ' :telephone_receiver: '},
		{name: 'Pager', openWith: ' :pager: '},
		{name: 'Fax', openWith: ' :fax: '},
		{name: 'Satellite', openWith: ' :satellite: '},
		{name: 'Tv', openWith: ' :tv: '},
		{name: 'Radio', openWith: ' :radio: '},
		{name: 'Sound Loud', openWith: ' :loud_sound: '},
		{name: 'Sound', openWith: ' :sound: '},
		{name: 'Speaker', openWith: ' :loudspeaker: '}, // альтернативы не нашел
		{name: 'Mute', openWith: ' :mute: '},
		{name: 'Bell', openWith: ' :bell: '},
		{name: 'No Bell', openWith: ' :no_bell: '},
		{name: 'Loudspeaker', openWith: ' :loudspeaker: '},
		{name: 'Mega', openWith: ' :mega: '},
		{name: 'Hourglass Flowing Sand', openWith: ' :hourglass_flowing_sand: '},
		{name: 'Hourglass', openWith: ' :hourglass: '},
		{name: 'Alarm Clock', openWith: ' :alarm_clock: '},
		{name: 'Watch', openWith: ' :watch: '},
		{name: 'Unlock', openWith: ' :unlock: '},
		{name: 'Lock', openWith: ' :lock: '},
		{name: 'Lock With Ink Pen', openWith: ' :lock_with_ink_pen: '},
		{name: 'Closed Lock With Key', openWith: ' :closed_lock_with_key: '},
		{name: 'Key', openWith: ' :key: '},
		{name: 'Mag Right', openWith: ' :mag_right: '},
		{name: 'Bulb', openWith: ' :bulb: '},
		{name: 'Flashlight', openWith: ' :flashlight: '},
		{name: 'High Brightness', openWith: ' :high_brightness: '},
		{name: 'Low Brightness', openWith: ' :low_brightness: '},
		{name: 'Electric Plug', openWith: ' :electric_plug: '},
		{name: 'Battery', openWith: ' :battery: '},
		{name: 'Mag', openWith: ' :mag: '},
		{name: 'Bathtub', openWith: ' :bathtub: '},
		{name: 'Bath', openWith: ' :bath: '},
		{name: 'Shower', openWith: ' :shower: '},
		{name: 'Toilet', openWith: ' :toilet: '},
		{name: 'Wrench', openWith: ' :wrench: '},
		{name: 'Nut and Bolt', openWith: ' :nut_and_bolt: '},
		{name: 'Hammer', openWith: ' :hammer: '},
		{name: 'Door', openWith: ' :door: '},
		{name: 'Smoking', openWith: ' :smoking: '},
		{name: 'Bomb', openWith: ' :bomb: '},
		{name: 'Gun', openWith: ' :gun: '},
		{name: 'Hocho', openWith: ' :knife: '},
		{name: 'Pill', openWith: ' :pill: '},
		{name: 'Syringe', openWith: ' :syringe: '},
		{name: 'Moneybag', openWith: ' :moneybag: '},
		{name: 'Yen', openWith: ' :yen: '},
		{name: 'Dollar', openWith: ' :dollar: '},
		{name: 'Pound', openWith: ' :pound: '},
		{name: 'Euro', openWith: ' :euro: '},
		{name: 'Credit Card', openWith: ' :credit_card: '},
		{name: 'Money With Wings', openWith: ' :money_with_wings: '},
		{name: 'Calling', openWith: ' :calling: '},
		{name: 'E-Mail', openWith: ' :email: '},
		{name: 'Inbox Tray', openWith: ' :inbox_tray: '},
		{name: 'Outbox Tray', openWith: ' :outbox_tray: '},
		{name: 'Envelope', openWith: ' :envelope: '},
		{name: 'Envelope With Arrow', openWith: ' :envelope_with_arrow: '},
		{name: 'Incoming Envelope', openWith: ' :incoming_envelope: '},
		{name: 'Postal Horn', openWith: ' :postal_horn: '},
		{name: 'Mailbox', openWith: ' :mailbox: '},
		{name: 'Mailbox Closed', openWith: ' :mailbox_closed: '},
		{name: 'Mailbox With Mail', openWith: ' :mailbox_with_mail: '},
		{name: 'Mailbox With No Mail', openWith: ' :mailbox_with_no_mail: '},
		{name: 'Postbox', openWith: ' :postbox: '},
		{name: 'Box', openWith: ' :package: '},
		{name: 'Pencil', openWith: ' :pencil: '},
		{name: 'Memo', openWith: ' :page_facing_up: '},
		{name: 'Page With Curl', openWith: ' :page_with_curl: '},
		{name: 'Bookmark Tabs', openWith: ' :bookmark_tabs: '},
		{name: 'Bar Chart', openWith: ' :bar_chart: '},
		{name: 'Chart With Upwards Trend', openWith: ' :chart_with_upwards_trend: '},
		{name: 'Chart With Downwards Trend', openWith: ' :chart_with_downwards_trend: '},
		{name: 'Scroll', openWith: ' :scroll: '},
		{name: 'Clipboard', openWith: ' :clipboard: '},
		{name: 'Date', openWith: ' :date: '},
		{name: 'Calendar', openWith: ' :calendar: '},
		{name: 'Card Index', openWith: ' :card_index: '},
		{name: 'File Folder', openWith: ' :file_folder: '},
		{name: 'Open File Folder', openWith: ' :open_file_folder: '},
		{name: 'Scissors', openWith: ' :scissors: '},
		{name: 'Pushpin', openWith: ' :pushpin: '},
		{name: 'Paperclip', openWith: ' :paperclip: '},
		{name: 'Black Nib', openWith: ' :black_nib: '},
		{name: 'Pencil2', openWith: ' :pencil2: '},
		{name: 'Straight Ruler', openWith: ' :straight_ruler: '},
		{name: 'Triangular Ruler', openWith: ' :triangular_ruler: '},
		{name: 'Closed Book', openWith: ' :closed_book: '},
		{name: 'Green Book', openWith: ' :green_book: '},
		{name: 'Blue Book', openWith: ' :blue_book: '},
		{name: 'Orange Book', openWith: ' :orange_book: '},
		{name: 'Notebook', openWith: ' :notebook: '},
		{name: 'Notebook With Decorative Cover', openWith: ' :notebook_with_decorative_cover: '},
		{name: 'Ledger', openWith: ' :ledger: '},
		{name: 'Books', openWith: ' :books: '},
		{name: 'Book', openWith: ' :book: '},
		{name: 'Bookmark', openWith: ' :bookmark: '},
		{name: 'Name Badge', openWith: ' :name_badge: '},
		{name: 'Microscope', openWith: ' :microscope: '},
		{name: 'Telescope', openWith: ' :telescope: '},
		{name: 'Newspaper', openWith: ' :newspaper: '},
		{name: 'Art', openWith: ' :art: '},
		{name: 'Clapper', openWith: ' :clapper: '},
		{name: 'Microphone', openWith: ' :microphone: '},
		{name: 'Headphones', openWith: ' :headphones: '},
		{name: 'Musical Score', openWith: ' :musical_score: '},
		{name: 'Musical Note', openWith: ' :musical_note: '},
		{name: 'Notes', openWith: ' :notes: '},
		{name: 'Musical Keyboard', openWith: ' :musical_keyboard: '},
		{name: 'Violin', openWith: ' :violin: '},
		{name: 'Trumpet', openWith: ' :trumpet: '},
		{name: 'Saxophone', openWith: ' :saxophone: '},
		{name: 'Guitar', openWith: ' :guitar: '},
		{name: 'Space Invader', openWith: ' :space_invader: '},
		{name: 'Video Game', openWith: ' :video_game: '},
		{name: 'Black Joker', openWith: ' :black_joker: '},
		{name: 'Flower Playing Cards', openWith: ' :flower_playing_cards: '},
		{name: 'Mahjong', openWith: ' :mahjong: '},
		{name: 'Game Die', openWith: ' :game_die: '},
		{name: 'Dart', openWith: ' :dart: '},
		{name: 'Football', openWith: ' :football: '},
		{name: 'Basketball', openWith: ' :basketball: '},
		{name: 'Soccer', openWith: ' :soccer: '},
		{name: 'Soccer', openWith: ' :soccer: '},
		{name: 'Baseball', openWith: ' :baseball: '},
		{name: 'Tennis', openWith: ' :tennis: '},
		{name: '8Ball', openWith: ' :8ball: '},
		{name: 'Rugby Football', openWith: ' :rugby_football: '},
		{name: 'Bowling', openWith: ' :bowling: '},
		{name: 'Golf', openWith: ' :golf: '},
		{name: 'Mountain Bicyclist', openWith: ' :mountain_bicyclist: '},
		{name: 'Bicyclist', openWith: ' :bicyclist: '},
		{name: 'Checkered Flag', openWith: ' :checkered_flag: '},
		{name: 'Horse Racing', openWith: ' :horse_racing: '},
		{name: 'Trophy', openWith: ' :trophy: '},
		{name: 'Ski', openWith: ' :ski: '},
		{name: 'Snowboarder', openWith: ' :snowboarder: '},
		{name: 'Swimmer', openWith: ' :swimmer: '},
		{name: 'Surfer', openWith: ' :surfer: '},
		{name: 'Fishing Pole and Fish', openWith: ' :fishing_pole_and_fish: '},
		{name: 'Coffee', openWith: ' :coffee: '},
		{name: 'Tea', openWith: ' :tea: '},
		{name: 'Sake', openWith: ' :sake: '},
		{name: 'Baby Bottle', openWith: ' :baby_bottle: '},
		{name: 'Beer', openWith: ' :beer: '},
		{name: 'Beers', openWith: ' :beers: '},
		{name: 'Cocktail', openWith: ' :cocktail: '},
		{name: 'Tropical Drink', openWith: ' :tropical_drink: '},
		{name: 'Wine Glass', openWith: ' :wine_glass: '},
		{name: 'Fork and Knife', openWith: ' :fork_and_knife: '},
		{name: 'Pizza', openWith: ' :pizza: '},
		{name: 'Hamburger', openWith: ' :hamburger: '},
		{name: 'Fries', openWith: ' :fries: '},
		{name: 'Poultry Leg', openWith: ' :poultry_leg: '},
		{name: 'Meat on Bone', openWith: ' :meat_on_bone: '},
		{name: 'Spaghetti', openWith: ' :spaghetti: '},
		{name: 'Curry', openWith: ' :curry: '},
		{name: 'Fried Shrimp', openWith: ' :fried_shrimp: '},
		{name: 'Bento', openWith: ' :bento: '},
		{name: 'Sushi', openWith: ' :sushi: '},
		{name: 'Fish Cake', openWith: ' :fish_cake: '},
		{name: 'Rice Ball', openWith: ' :rice_ball: '},
		{name: 'Rice Cracker', openWith: ' :rice_cracker: '},
		{name: 'Rice', openWith: ' :rice: '},
		{name: 'Ramen', openWith: ' :ramen: '},
		{name: 'Stew', openWith: ' :stew: '},
		{name: 'Oden', openWith: ' :oden: '},
		{name: 'Dango', openWith: ' :dango: '},
		{name: 'Egg', openWith: ' :egg: '},
		{name: 'Bread', openWith: ' :bread: '},
		{name: 'Doughnut', openWith: ' :doughnut: '},
		{name: 'Custard', openWith: ' :custard: '},
		{name: 'Icecream', openWith: ' :icecream: '},
		{name: 'Ice Cream', openWith: ' :ice_cream: '},
		{name: 'Shaved Ice', openWith: ' :shaved_ice: '},
		{name: 'Birthday', openWith: ' :birthday: '},
		{name: 'Cake', openWith: ' :cake: '},
		{name: 'Cookie', openWith: ' :cookie: '},
		{name: 'Chocolate Bar', openWith: ' :chocolate_bar: '},
		{name: 'Candy', openWith: ' :candy: '},
		{name: 'Lollipop', openWith: ' :lollipop: '},
		{name: 'Honey Pot', openWith: ' :honey_pot: '},
		{name: 'Apple', openWith: ' :apple: '},
		{name: 'Green Apple', openWith: ' :green_apple: '},
		{name: 'Tangerine', openWith: ' :tangerine: '},
		{name: 'Lemon', openWith: ' :lemon: '},
		{name: 'Cherries', openWith: ' :cherries: '},
		{name: 'Grapes', openWith: ' :grapes: '},
		{name: 'Watermelon', openWith: ' :watermelon: '},
		{name: 'Strawberry', openWith: ' :strawberry: '},
		{name: 'Peach', openWith: ' :peach: '},
		{name: 'Melon', openWith: ' :melon: '},
		{name: 'Banana', openWith: ' :banana: '},
		{name: 'Pear', openWith: ' :pear: '},
		{name: 'Pineapple', openWith: ' :pineapple: '},
		{name: 'Sweet Potato', openWith: ' :sweet_potato: '},
		{name: 'Eggplant', openWith: ' :eggplant: '},
		{name: 'Tomato', openWith: ' :tomato: '},
		{name: 'Corn', openWith: ' :corn: '}
	]},
	{name: 'Places', className:'emoji-places', dropMenu: [
		{name: 'House', openWith: ' :house: '},
		{name: 'House With Garden', openWith: ' :house_with_garden: '},
		{name: 'School', openWith: ' :school: '},
		{name: 'Office', openWith: ' :office: '},
		{name: 'Post Office', openWith: ' :post_office: '},
		{name: 'Hospital', openWith: ' :hospital: '},
		{name: 'Bank', openWith: ' :bank: '},
		{name: 'Convenience Store', openWith: ' :convenience_store: '},
		{name: 'Love Hotel', openWith: ' :love_hotel: '},
		{name: 'Hotel', openWith: ' :hotel: '},
		{name: 'Wedding', openWith: ' :wedding: '},
		{name: 'Church', openWith: ' :church: '},
		{name: 'Department Store', openWith: ' :department_store: '},
		{name: 'European Post Office', openWith: ' :european_post_office: '},
		{name: 'City Sunrise', openWith: ' :city_sunrise: '},
		{name: 'City Sunset', openWith: ' :city_sunset: '},
		{name: 'Japanese Castle', openWith: ' :japanese_castle: '},
		{name: 'European Castle', openWith: ' :european_castle: '},
		{name: 'Tent', openWith: ' :tent: '},
		{name: 'Factory', openWith: ' :factory: '},
		{name: 'Tokyo Tower', openWith: ' :tokyo_tower: '},
		{name: 'Japan', openWith: ' :japan: '},
		{name: 'Mount Fuji', openWith: ' :mount_fuji: '},
		{name: 'Sunrise over Mountains', openWith: ' :sunrise_over_mountains: '},
		{name: 'Sunrise', openWith: ' :sunrise: '},
		{name: 'City at Night', openWith: ' :night_with_stars: '},
		{name: 'Statue of Liberty', openWith: ' :statue_of_liberty: '},
		{name: 'Bridge at Night', openWith: ' :bridge_at_night: '},
		{name: 'Carousel Horse', openWith: ' :carousel_horse: '},
		{name: 'Ferris Wheel', openWith: ' :ferris_wheel: '},
		{name: 'Fountain', openWith: ' :fountain: '},
		{name: 'Roller Coaster', openWith: ' :roller_coaster: '},
		{name: 'Ship', openWith: ' :ship: '},
		{name: 'Sailboat', openWith: ' :sailboat: '},
		{name: 'Speedboat', openWith: ' :speedboat: '},
		{name: 'Rowboat', openWith: ' :rowboat: '},
		{name: 'Anchor', openWith: ' :anchor: '},
		{name: 'Rocket', openWith: ' :rocket: '},
		{name: 'Airplane', openWith: ' :airplane: '},
		{name: 'Seat', openWith: ' :seat: '},
		{name: 'Helicopter', openWith: ' :helicopter: '},
		{name: 'Steam Locomotive', openWith: ' :steam_locomotive: '},
		{name: 'Tram', openWith: ' :tram: '},
		{name: 'Station', openWith: ' :station: '},
		{name: 'Mountain Railway', openWith: ' :mountain_railway: '},
		{name: 'Train2', openWith: ' :train2: '},
		{name: 'Bullettrain Side2', openWith: ' :bullettrain_side:  '},
		{name: 'Bullettrain Side', openWith: ' :bullettrain_front:  '},
		{name: 'Light Rail', openWith: ' :light_rail: '},
		{name: 'Train Front', openWith: ' :metro: '},
		{name: 'Monorail', openWith: ' :monorail: '},
		{name: 'Train', openWith: ' :railway_car: '},
		{name: 'Trolley', openWith: ' :trolleybus: '},
		{name: 'Trolleybus', openWith: ' :trolleybus: '},
		{name: 'Bus', openWith: ' :bus: '},
		{name: 'Oncoming Bus', openWith: ' :oncoming_bus: '},
		{name: 'Blue Car', openWith: ' :blue_car: '},
		{name: 'Oncoming Automobile', openWith: ' :oncoming_automobile: '},
		{name: 'Car', openWith: ' :red_car: '},
		{name: 'Taxi', openWith: ' :taxi: '},
		{name: 'Oncoming Taxi', openWith: ' :oncoming_taxi: '},
		{name: 'Articulated Lorry', openWith: ' :articulated_lorry: '},
		{name: 'Truck', openWith: ' :truck: '},
		{name: 'Rotating Light', openWith: ' :rotating_light: '},
		{name: 'Police Car', openWith: ' :police_car: '},
		{name: 'Oncoming Police Car', openWith: ' :oncoming_police_car: '},
		{name: 'Fire Engine', openWith: ' :fire_engine: '},
		{name: 'Ambulance', openWith: ' :ambulance: '},
		{name: 'Minibus', openWith: ' :minibus: '},
		{name: 'Bike', openWith: ' :bike: '},
		{name: 'Aerial Tramway', openWith: ' :aerial_tramway: '},
		{name: 'Suspension Railway', openWith: ' :suspension_railway: '},
		{name: 'Mountain Cableway', openWith: ' :mountain_cableway: '},
		{name: 'Tractor', openWith: ' :tractor: '},
		{name: 'Barber', openWith: ' :barber: '},
		{name: 'Busstop', openWith: ' :busstop: '},
		{name: 'Ticket', openWith: ' :ticket: '},
		{name: 'Vertical Traffic Light', openWith: ' :vertical_traffic_light: '},
		{name: 'Traffic Light', openWith: ' :traffic_light: '},
		{name: 'Warning', openWith: ' :warning: '},
		{name: 'Construction', openWith: ' :construction: '},
		{name: 'Beginner', openWith: ' :beginner: '},
		{name: 'Fuelpump', openWith: ' :fuelpump: '},
		{name: 'Izakaya Lantern', openWith: ' :izakaya_lantern: '},
		{name: 'Slot Machine', openWith: ' :slot_machine: '},
		{name: 'Hotsprings', openWith: ' :hotsprings: '},
		{name: 'Moyai', openWith: ' :moyai: '},
		{name: 'Circus Tent', openWith: ' :circus_tent: '},
		{name: 'Performing Arts', openWith: ' :performing_arts: '},
		{name: 'Round Pushpin', openWith: ' :round_pushpin: '},
		{name: 'Triangular Flag on Post', openWith: ' :triangular_flag_on_post: '},
		{name: 'Jp', openWith: ' :jp: '},
		{name: 'Kr', openWith: ' :kr: '},
		{name: 'De', openWith: ' :de: '},
		{name: 'Cn', openWith: ' :cn: '},
		{name: 'Us', openWith: ' :us: '},
		{name: 'Fr', openWith: ' :fr: '},
		{name: 'Es', openWith: ' :es: '},
		{name: 'It', openWith: ' :it: '},
		{name: 'Ru', openWith: ' :ru: '},
		{name: 'Gb', openWith: ' :gb: '}
	]},
	{name: 'Symbols', className:'emoji-symbols', dropMenu: [
		{name: 'One', openWith: ' :one: '},
		{name: 'Two', openWith: ' :two: '},
		{name: 'Three', openWith: ' :three: '},
		{name: 'Four', openWith: ' :four: '},
		{name: 'Five', openWith: ' :five: '},
		{name: 'Six', openWith: ' :six: '},
		{name: 'Seven', openWith: ' :seven: '},
		{name: 'Eight', openWith: ' :eight: '},
		{name: 'Nine', openWith: ' :nine: '},
		{name: 'Zero', openWith: ' :zero: '},
		{name: 'Keycap Ten', openWith: ' :keycap_ten: '},
		{name: '1234', openWith: ' :1234: '},
		{name: 'Hash', openWith: ' :hash: '},
		{name: 'Symbols', openWith: ' :symbols: '},
		{name: 'Arrow up', openWith: ' :arrow_up: '},
		{name: 'Arrow Down', openWith: ' :arrow_down: '},
		{name: 'Arrow Left', openWith: ' :arrow_left: '},
		{name: 'Arrow Right', openWith: ' :arrow_right: '},
		{name: 'Capital Abcd', openWith: ' :capital_abcd: '},
		{name: 'Abcd', openWith: ' :abcd: '},
		{name: 'Abc', openWith: ' :abc: '},
		{name: 'Arrow Upper Right', openWith: ' :arrow_upper_right: '},
		{name: 'Arrow Upper Left', openWith: ' :arrow_upper_left: '},
		{name: 'Arrow Lower Right', openWith: ' :arrow_lower_right: '},
		{name: 'Arrow Lower Left', openWith: ' :arrow_lower_left: '},
		{name: 'Left Right Arrow', openWith: ' :left_right_arrow: '},
		{name: 'Arrow up Down', openWith: ' :arrow_up_down: '},
		{name: 'Arrows Counterclockwise', openWith: ' :arrows_counterclockwise: '},
		{name: 'Arrow Backward', openWith: ' :arrow_backward: '},
		{name: 'Arrow Forward', openWith: ' :arrow_forward: '},
		{name: 'Arrow up Small', openWith: ' :arrow_up_small: '},
		{name: 'Arrow Down Small', openWith: ' :arrow_down_small: '},
		{name: 'Leftwards Arrow With Hook', openWith: ' :leftwards_arrow_with_hook: '},
		{name: 'Arrow Right Hook', openWith: ' :arrow_right_hook: '},
		{name: 'Information Source', openWith: ' :information_source: '},
		{name: 'Rewind', openWith: ' :rewind: '},
		{name: 'Fast Forward', openWith: ' :fast_forward: '},
		{name: 'Arrow Double up', openWith: ' :arrow_double_up: '},
		{name: 'Arrow Double Down', openWith: ' :arrow_double_down: '},
		{name: 'Arrow Heading Down', openWith: ' :arrow_heading_down: '},
		{name: 'Arrowing Heading up', openWith: ' :arrow_heading_up: '},
		{name: 'Ok', openWith: ' :ok: '},
		{name: 'Twisted Rightwards Arrows', openWith: ' :twisted_rightwards_arrows: '},
		{name: 'Repeat', openWith: ' :repeat: '},
		{name: 'Repeat One', openWith: ' :repeat_one: '},
		{name: 'New', openWith: ' :new: '},
		{name: 'up', openWith: ' :up: '},
		{name: 'Cool', openWith: ' :cool: '},
		{name: 'Free', openWith: ' :free: '},
		{name: 'Ng', openWith: ' :ng: '},
		{name: 'Signal Strength', openWith: ' :signal_strength: '},
		{name: 'Cinema', openWith: ' :cinema: '},
		{name: 'Koko', openWith: ' :koko: '},
		{name: 'U6307', openWith: ' :u6307: '},
		{name: 'U7a7a', openWith: ' :u7a7a: '},
		{name: 'U6E80', openWith: ' :u6e80: '},
		{name: 'U5408', openWith: ' :u5408: '},
		{name: 'U7981', openWith: ' :u7981: '},
		{name: 'Ideograph Advantage', openWith: ' :ideograph_advantage: '},
		{name: 'U5272', openWith: ' :u5272: '},
		{name: 'U55B6', openWith: ' :u55b6: '},
		{name: 'U6709', openWith: ' :u6709: '},
		{name: 'U7121', openWith: ' :u7121: '},
		{name: 'Restroom', openWith: ' :restroom: '},
		{name: 'Mens', openWith: ' :mens: '},
		{name: 'Womens', openWith: ' :womens: '},
		{name: 'Baby Symbol', openWith: ' :baby_symbol: '},
		{name: 'Wc', openWith: ' :wc: '},
		{name: 'Potable Water', openWith: ' :potable_water: '},
		{name: 'Put Litter in Its Place', openWith: ' :put_litter_in_its_place: '},
		{name: 'Parking', openWith: ' :parking: '},
		{name: 'Wheelchair', openWith: ' :wheelchair: '},
		{name: 'No Smoking', openWith: ' :no_smoking: '},
		{name: 'U6708', openWith: ' :u6708: '},
		{name: 'U7533', openWith: ' :u7533: '},
		{name: 'Sa', openWith: ' :sa: '},
		{name: 'M', openWith: ' :m: '},
		{name: 'Passport Control', openWith: ' :passport_control: '},
		{name: 'Baggage Claim', openWith: ' :baggage_claim: '},
		{name: 'Left Luggage', openWith: ' :left_luggage: '},
		{name: 'Customs', openWith: ' :customs: '},
		{name: 'Accept', openWith: ' :accept: '},
		{name: 'Secret', openWith: ' :secret: '},
		{name: 'Congratulations', openWith: ' :congratulations: '},
		{name: 'Cl', openWith: ' :cl: '},
		{name: 'Sos', openWith: ' :sos: '},
		{name: 'Id', openWith: ' :id: '},
		{name: 'No Entry Sign', openWith: ' :no_entry_sign: '},
		{name: 'Underage', openWith: ' :underage: '},
		{name: 'No Mobile Phones', openWith: ' :no_mobile_phones: '},
		{name: 'Do Not Litter', openWith: ' :do_not_litter: '},
		{name: 'Non-Potable Water', openWith: ' :non-potable_water: '},
		{name: 'No Bicycles', openWith: ' :no_bicycles: '},
		{name: 'No Pedestrians', openWith: ' :no_pedestrians: '},
		{name: 'Children Crossing', openWith: ' :children_crossing: '},
		{name: 'No Entry', openWith: ' :no_entry: '},
		{name: 'Eight Spoked Asterisk', openWith: ' :eight_spoked_asterisk: '},
		{name: 'Four Spoked Asterisk', openWith: ' :sparkle: '},
		{name: 'Negative Squared Cross Mark', openWith: ' :negative_squared_cross_mark: '},
		{name: 'White Check Mark', openWith: ' :white_check_mark: '},
		{name: 'Eight Pointed Black Star', openWith: ' :eight_pointed_black_star: '},
		{name: 'Heart Decoration', openWith: ' :heart_decoration: '},
		{name: 'Vs', openWith: ' :vs: '},
		{name: 'Vibration Mode', openWith: ' :vibration_mode: '},
		{name: 'Mobile Phone off', openWith: ' :mobile_phone_off: '},
		{name: 'a', openWith: ' :a: '},
		{name: 'B', openWith: ' :b: '},
		{name: 'Ab', openWith: ' :ab: '},
		{name: 'O2', openWith: ' :o2: '},
		{name: 'Diamond Shape With a Dot Inside', openWith: ' :diamond_shape_with_a_dot_inside: '},
		{name: 'Curly Loop', openWith: ' :curly_loop: '},
		{name: 'Recycle', openWith: ' :recycle: '},
		{name: 'Aries', openWith: ' :aries: '},
		{name: 'Taurus', openWith: ' :taurus: '},
		{name: 'Gemini', openWith: ' :gemini: '},
		{name: 'Cancer', openWith: ' :cancer: '},
		{name: 'Leo', openWith: ' :leo: '},
		{name: 'Virgo', openWith: ' :virgo: '},
		{name: 'Libra', openWith: ' :libra: '},
		{name: 'Scorpius', openWith: ' :scorpius: '},
		{name: 'Sagittarius', openWith: ' :sagittarius: '},
		{name: 'Capricorn', openWith: ' :capricorn: '},
		{name: 'Aquarius', openWith: ' :aquarius: '},
		{name: 'Pisces', openWith: ' :pisces: '},
		{name: 'Ophiuchus', openWith: ' :ophiuchus: '},
		{name: 'Six Pointed Star', openWith: ' :six_pointed_star: '},
		{name: 'Atm', openWith: ' :atm: '},
		{name: 'Chart', openWith: ' :chart: '},
		{name: 'Heavy Dollar Sign', openWith: ' :heavy_dollar_sign: '},
		{name: 'Currency Exchange', openWith: ' :currency_exchange: '},
		{name: 'Copyright', openWith: ' :copyright: '},
		{name: 'Registered', openWith: ' :registered: '},
		{name: 'Tm', openWith: ' :tm: '},
		{name: 'X', openWith: ' :x: '},
		{name: 'Bangbang', openWith: ' :bangbang: '},
		{name: 'Interrobang', openWith: ' :interrobang: '},
		{name: 'Heavy Exclamation Mark', openWith: ' :exclamation: '},
		{name: 'Heavy Question Mark', openWith: ' :question: '},
		{name: 'Gray Exclamation Mark', openWith: ' :grey_exclamation: '},
		{name: 'Gray Question Mark', openWith: ' :grey_question: '},
		{name: 'O', openWith: ' :o: '},
		{name: 'Top', openWith: ' :top: '},
		{name: 'End', openWith: ' :end: '},
		{name: 'Back', openWith: ' :back: '},
		{name: 'on', openWith: ' :on: '},
		{name: 'Soon', openWith: ' :soon: '},
		{name: 'Arrows Clockwise', openWith: ' :arrows_clockwise: '},
		{name: 'Clock12', openWith: ' :clock12: '},
		{name: 'Clock1230', openWith: ' :clock1230: '},
		{name: 'Clock1', openWith: ' :clock1: '},
		{name: 'Clock130', openWith: ' :clock130: '},
		{name: 'Clock2', openWith: ' :clock2: '},
		{name: 'Clock230', openWith: ' :clock230: '},
		{name: 'Clock3', openWith: ' :clock3: '},
		{name: 'Clock330', openWith: ' :clock330: '},
		{name: 'Clock4', openWith: ' :clock4: '},
		{name: 'Clock430', openWith: ' :clock430: '},
		{name: 'Clock5', openWith: ' :clock5: '},
		{name: 'Clock530', openWith: ' :clock530: '},
		{name: 'Clock6', openWith: ' :clock6: '},
		{name: 'Clock7', openWith: ' :clock7: '},
		{name: 'Clock8', openWith: ' :clock8: '},
		{name: 'Clock9', openWith: ' :clock9: '},
		{name: 'Clock10', openWith: ' :clock10: '},
		{name: 'Clock11', openWith: ' :clock11: '},
		{name: 'Clock630', openWith: ' :clock630: '},
		{name: 'Clock730', openWith: ' :clock730: '},
		{name: 'Clock830', openWith: ' :clock830: '},
		{name: 'Clock930', openWith: ' :clock930: '},
		{name: 'Clock1030', openWith: ' :clock1030: '},
		{name: 'Clock1130', openWith: ' :clock1130: '},
		{name: 'Heavy Multiplication X', openWith: ' :heavy_multiplication_x: '},
		{name: 'Heavy Plus Sign', openWith: ' :heavy_plus_sign: '},
		{name: 'Heavy Minus Sign', openWith: ' :heavy_minus_sign: '},
		{name: 'Heavy Division Sign', openWith: ' :heavy_division_sign: '},
		{name: 'Spades', openWith: ' :spades: '},
		{name: 'Hearts', openWith: ' :hearts: '},
		{name: 'Clubs', openWith: ' :clubs: '},
		{name: 'Diamonds', openWith: ' :diamonds: '},
		{name: 'White Flower', openWith: ' :white_flower: '},
		{name: '100', openWith: ' :100: '},
		{name: 'Heavy Check Mark', openWith: ' :heavy_check_mark: '},
		{name: 'Ballot Box With Check', openWith: ' :ballot_box_with_check: '},
		{name: 'Radio Button', openWith: ' :radio_button: '},
		{name: 'Link', openWith: ' :link: '},
		{name: 'Curly Loop', openWith: ' :curly_loop: '},
		{name: 'Wavy Dash', openWith: ' :wavy_dash: '},
		{name: 'Part Alternation Mark', openWith: ' :part_alternation_mark: '},
		{name: 'Trident', openWith: ' :trident: '},
		{name: 'Black Square With Border', openWith: ' :black_square_button: '},
		{name: 'White Square With Border', openWith: ' :white_square_button: '},
		{name: 'Black Square Small', openWith: ' :black_medium_square: '},
		{name: 'White Square Small', openWith: ' :white_medium_square: '},
		{name: 'Black Square Smaller', openWith: ' :black_medium_small_square: '},
		{name: 'White Square Smaller', openWith: ' :white_medium_small_square: '},
		{name: 'Small Red Triangle', openWith: ' :small_red_triangle: '},
		{name: 'Black Square Button', openWith: ' :black_square_button: '},
		{name: 'White Square Button', openWith: ' :white_square_button: '},
		{name: 'Black Circle', openWith: ' :black_circle: '},
		{name: 'White Circle', openWith: ' :white_circle: '},
		{name: 'Red Circle', openWith: ' :red_circle: '},
		{name: 'Large Blue Circle', openWith: ' :large_blue_circle: '},
		{name: 'Small Red Triangle Down', openWith: ' :small_red_triangle_down: '},
		{name: 'White Square', openWith: ' :white_large_square: '},
		{name: 'Black Square', openWith: ' :black_large_square: '},
		{name: 'Large Orange Diamond', openWith: ' :large_orange_diamond: '},
		{name: 'Large Blue Diamond', openWith: ' :large_blue_diamond: '},
		{name: 'Small Orange Diamond', openWith: ' :small_orange_diamond: '},
		{name: 'Small Blue Diamond', openWith: ' :small_blue_diamond: '}
	]},

]

var newMarkitupSettings = ls.settings.getMarkitup();
var newMarkitupSettingsComment = ls.settings.getMarkitupComment();

ls.settings.getMarkitup = function() {
    newMarkitupSettings.markupSet = newMarkitupSettings.markupSet.concat(myMarkupSet);
    return newMarkitupSettings;
}

ls.settings.getMarkitupComment = function() {
	newMarkitupSettingsComment.markupSet = newMarkitupSettingsComment.markupSet.concat(myMarkupSet);
	return newMarkitupSettingsComment;
}

if(ls.forum !== undefined) {
	var newMarkitupSettingsForum = ls.forum.getMarkitup();
	var newMarkitupSettingsMini = ls.forum.getMarkitupMini();

	ls.forum.getMarkitup = function() {
		newMarkitupSettingsForum.markupSet = newMarkitupSettingsForum.markupSet.concat(
			[{separator: '---------------'}, {name:'dummy', className:'dummy', openWith: ' :poop: '}], // Заглушка вместо cut
			myMarkupSet
		); 
		return newMarkitupSettingsForum;
	}

	ls.forum.getMarkitupMini = function() {
		newMarkitupSettingsMini.markupSet = newMarkitupSettingsMini.markupSet.concat(
			[{separator: '---------------'}, {name:'dummy', className:'dummy', openWith: ' :poop: '}], [{name:'dummy', className:'dummy', openWith: ' :poop: '}], // Заглушка
			myMarkupSet
		);
		return newMarkitupSettingsMini;
	}
}